# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec80c696ce1c819e7edc2c350439c559cbee18fb34148d8ce1c39369301a7f4c7d78f961e1337ae41bc79161f054e1207c6e41105b6dcadd54fa7fa35f0413f

test:
  secret_key_base: 9d1647ad52014e448e25f7a169076af448ed7c745dba591e1964d88246cde7f025c33d176d1fca5240cc425707be82a00176fd228b369e291593b8dc5fbe931e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
